# Generated by Django 5.0.6 on 2026-07-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='dateofbirth',
            field=models.DateTimeField(null=True),
        ),
    ]
