# Generated by Django 5.0.6 on 2026-07-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccc', '0002_members_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='residence',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
