# Generated by Django 5.0.6 on 2026-07-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccc', '0003_members_residence'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateTimeField(null=True)),
                ('starttime', models.TimeField(null=True)),
                ('endtime', models.TimeField(null=True)),
                ('location', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=10)),
            ],
        ),
    ]
