# Generated by Django 5.0.6 on 2026-07-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccc', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
