# Generated by Django 5.0.6 on 2026-07-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccc', '0005_members_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='scd_group',
            new_name='group',
        ),
    ]
