# Generated by Django 5.0.6 on 2026-07-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccc', '0006_rename_scd_group_members_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='group',
            new_name='scd_group',
        ),
    ]
