# Generated by Django 5.0.6 on 2026-07-23 18:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccc', '0007_rename_group_members_scd_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_present', models.BooleanField(default=False)),
                ('marked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='ccc.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='ccc.members')),
            ],
            options={
                'unique_together': {('member', 'event')},
            },
        ),
    ]
