# Generated by Django 5.0.6 on 2026-07-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccc', '0008_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
