# Generated by Django 5.0.6 on 2026-07-24 14:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccc', '0009_alter_members_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('member_added', 'New Member'), ('event_created', 'Event Created'), ('attendance_taken', 'Attendance Taken')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('icon', models.CharField(default='info', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
