# Generated by Django 5.0.6 on 2026-07-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccc', '0010_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='membership_status',
            field=models.CharField(default='active', max_length=100),
        ),
    ]
