# Generated by Django 5.0.6 on 2026-07-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccc', '0011_membership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
