# Generated by Django 5.0.6 on 2026-07-25 14:36

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccc', '0012_members_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('donor_name', models.CharField(blank=True, max_length=150)),
                ('fund', models.CharField(choices=[('general', 'General Fund'), ('building', 'Building Fund'), ('missions', 'Missions'), ('youth', 'Youth Ministry'), ('benevolence', 'Benevolence')], default='general', max_length=30)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('check', 'Check'), ('ach', 'ACH'), ('card', 'Card')], default='cash', max_length=20)),
                ('gift_date', models.DateField(default=django.utils.timezone.localdate)),
                ('tax_deductible', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
