# Generated by Django 5.0.6 on 2026-07-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccc', '0013_givingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='actor',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
