# Generated by Django 5.0.6 on 2026-07-25 18:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccc', '0014_activitylog_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
