# Generated by Django 5.0.6 on 2026-07-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccc', '0015_alter_members_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='givingrecord',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Donation'), ('expense', 'Deduction')], default='income', max_length=10),
        ),
    ]
