# Generated by Django 5.0.6 on 2026-08-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccc', '0016_givingrecord_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(max_length=30),
        ),
    ]
